# Generated by Django 3.1.1 on 2021-09-28 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMachineLearningProcessado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.TextField(null=True, verbose_name='Identificador do modelo')),
                ('auc', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='aux')),
                ('logloss', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='logloss')),
                ('aucpr', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='aucpr')),
                ('mean_per_class_error', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='mean_per_class_error')),
                ('rmse', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='rmse')),
                ('mse', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='mse')),
                ('binario_modelo', models.FileField(null=True, upload_to='binario_modelo_ml', verbose_name='Binário do modelo ML')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessamentoModeloMachineLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora do processamento')),
                ('dados_csv', models.FileField(upload_to='arquivos_csv', verbose_name='Arquivo CSV')),
                ('classe', models.CharField(max_length=30, verbose_name='Classe')),
                ('variaveis_independentes', models.TextField(null=True, verbose_name='Variáveis independentes')),
                ('tempo_maximo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(600)], verbose_name='Tempo máximo em segundos')),
                ('modelos_processados', models.ManyToManyField(to='ia.ModeloMachineLearningProcessado')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
